# Generated by Django 5.1.2 on 2024-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='accountno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
