# Generated by Django 5.1.2 on 2024-10-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_accountholder_accountno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='accountno',
            field=models.IntegerField(unique=True),
        ),
    ]
