# Generated by Django 5.1.2 on 2024-10-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_accountholder_accountno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='accountno',
            field=models.IntegerField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='mobileno',
            field=models.IntegerField(max_length=10),
        ),
    ]
