# Generated by Django 5.1.2 on 2024-10-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_accountholder_accountno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='mobileno',
        ),
    ]
