# Generated by Django 5.1.2 on 2024-10-23 18:28

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_accountholder_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='phone_number',
            field=models.CharField(default='9999999999', max_length=10, validators=[homepage.models.validate_10_digits]),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='accountno',
            field=models.CharField(help_text='Enter exactly 11 digits for the account number.', max_length=11, unique=True, validators=[homepage.models.validate_11_digits]),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
